package com.example.backpackapp.units

object Parameters {
    const val TAG = "Connect_Firebase"
    const val REGISTER_FAIL = "Registration failed password should be at least 6 characters"
    const val CHECK_PASSWORD = "Password should be at least 6 characters"
    const val SUCCESSFUL_REGISTRATION = "successful registration"
    const val EMPTY_PHONE_NUMBER = "You have not entered your phone number"
    const val CHECK_INPUT_INFORMATION = "You have not entered enough information"
    const val CHECK_LOGIN_FAIl = "Bad account name or password"
    const val CHECK_LOGIN_SUCCESS = "Logged in successfully"
    const val TAG_COMEBACK = "MY_APP_TAG"
    const val BIOMETRIC_SUCCESS = "App can authenticate using biometrics."
    const val BIOMETRIC_ERROR_NO_HARDWARE = "No biometric features available on this device."
    const val BIOMETRIC_ERROR_HW_UNAVAILABLE = "Biometric features are currently unavailable."
    const val BIOMETRIC_TITLE = "BackPack Login"
    const val BIOMETRIC_LOGIN_SUBTITLE = "Login using your biometric credential"
    const val TEXT_NEGATIVE_BUTTON = "Cancel"
    const val CHECK_CONNECT = "No network connection"
    const val CHECK_PERMISSION = "you have not granted access"
    const val TITLE_INTENT_RESULT_LAUNCHER = "Select picture"
    const val UPDATE_PROFILE_SUCCESS = "User profile updated"
    const val CREATE_USER_WITH_EMAIL_SUCCESS = "createUserWithEmail:success"
    const val CREATE_USER_WITH_EMAIL_FAIL = "createUserWithEmail:failure"
    const val SIGN_IN_WITH_EMAIL_SUCCESS = "signInWithEmail:success"
    const val SIGN_IN_WITH_EMAIL_FAIL = "signInWithEmail:failure"
    const val CHECK_ENTERED_NUMBER_PHONE = "The phone number you just entered is not valid"
    const val CHECK_ENTERED_EMAIL_PASSWORD_LOGIN = "Can't leave any fields blank"
    const val WAIT_DATA_IS_LOADING = "Please wait a moment while the data is loading"
    const val LOADING_DATA = "Loading....."
    const val CHECK_FORMAT_EMAIL_REGISTER = "Email format is not correct"
    const val IS_EMPTY = ""
    const val PATTERN_TIME_FORMAT = "hh:mma"
    const val PATTERN_DATE_FORMAT = "dd-mm-yyyy"
    const val TIME_SEND_MESSAGE = "timeSendMessage"
    const val USERS = "Users"
    const val AVATAR_USERS = "avatarUser"
    const val NAME_USERS = "nameUser"
    const val RATING_START = "rating"
    const val URL = "url"
    const val UID = "uid"
    const val MUSIC_FOR_YOU = "music_for_you"
    const val LIST_MUSIC = "list_music"
    const val ALL_TRACKS = "all_tracks"
    const val PERMISSION_FAIL = "User denied access"
}